import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { toast } from "sonner";
import { apiClient } from "@/service/apiClient";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import type { Company } from "@/types/company";

const SCHEMA = z.object({
  invoiceHeaderSubtitle: z.string().max(200).optional(),
  invoiceNotesUnpaid: z.string().max(1000).optional(),
  invoiceNotesPaid: z.string().max(1000).optional(),
  invoiceTerms: z.string().max(4000).optional(),
  invoiceFooterSignatureNote: z.string().max(300).optional(),
  invoiceQrEnabled: z.boolean(),
});

type FormData = z.infer<typeof SCHEMA>;

type Props = {
  company: Company;
  onSaved: (company: Company) => void;
};

export function InvoiceBrandingSettingsCard({ company, onSaved }: Props) {
  const [saving, setSaving] = useState(false);

  const form = useForm<FormData>({
    resolver: zodResolver(SCHEMA),
    defaultValues: {
      invoiceHeaderSubtitle: "",
      invoiceNotesUnpaid: "",
      invoiceNotesPaid: "",
      invoiceTerms: "",
      invoiceFooterSignatureNote: "",
      invoiceQrEnabled: false,
    },
  });

  useEffect(() => {
    form.reset({
      invoiceHeaderSubtitle: company.invoiceHeaderSubtitle || "",
      invoiceNotesUnpaid: company.invoiceNotesUnpaid || "",
      invoiceNotesPaid: company.invoiceNotesPaid || "",
      invoiceTerms: company.invoiceTerms || "",
      invoiceFooterSignatureNote: company.invoiceFooterSignatureNote || "",
      invoiceQrEnabled: !!company.invoiceQrEnabled,
    });
  }, [company, form]);

  const onSubmit = async (values: FormData) => {
    try {
      setSaving(true);
      const res = await apiClient.put<Company>(
        `/companies/${company.id}/invoice-branding`,
        values,
      );
      toast.success("Invoice branding settings updated");
      onSaved(res.data);
    } catch (error) {
      console.error(error);
      toast.error("Failed to save invoice branding settings");
    } finally {
      setSaving(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg">Invoice Branding & Footer</CardTitle>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form className="space-y-4" onSubmit={form.handleSubmit(onSubmit)}>
            <FormField
              control={form.control}
              name="invoiceHeaderSubtitle"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Header Subtitle</FormLabel>
                  <FormControl>
                    <Input placeholder="Invoice generated by ERP system" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="invoiceNotesUnpaid"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Notes Template (Unpaid)</FormLabel>
                  <FormControl>
                    <Textarea
                      rows={4}
                      placeholder="Use placeholders like {{companyName}}, {{invoiceDate}}, {{dueDate}}, {{invoiceId}}"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="invoiceNotesPaid"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Notes Template (Paid)</FormLabel>
                  <FormControl>
                    <Textarea
                      rows={3}
                      placeholder="Use placeholders like {{companyName}}, {{invoiceId}}, {{paidDate}}"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="invoiceTerms"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Terms & Conditions (one line per item)</FormLabel>
                  <FormControl>
                    <Textarea rows={8} placeholder="Line 1&#10;Line 2&#10;Line 3" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="invoiceFooterSignatureNote"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Footer Signature Note</FormLabel>
                  <FormControl>
                    <Input
                      placeholder="This is a computer-generated document and does not require a physical signature."
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="invoiceQrEnabled"
              render={({ field }) => (
                <FormItem className="flex items-center gap-2 space-y-0">
                  <FormControl>
                    <input
                      type="checkbox"
                      checked={field.value}
                      onChange={(e) => field.onChange(e.target.checked)}
                      className="h-4 w-4"
                    />
                  </FormControl>
                  <FormLabel className="m-0">Enable QR in invoice footer</FormLabel>
                </FormItem>
              )}
            />

            <Button type="submit" disabled={saving}>
              {saving ? "Saving..." : "Save Invoice Branding"}
            </Button>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
}
